#!/usr/bin/env python3
"""Regime witness reconciliation (D-0078 amendment evidence).

Generates report/exhibits/regime-witness.md from pinned CSVs only —
never the working tree. One row per campaign: the safe arm's per-trial
page_verify witness (median, range, uniformity) beside the canary
columns where the pinned runs.csv carries them. Rows are grouped by
kernel family (the safe arm's kernel_sha256) because witness absolutes
compare only within one family; the regime divide is stated per family
and only where that family exhibits both clusters or a corroborating
in-family boot record.

Fail-closed: a pin that does not load, a campaign with no recorded
safe-arm rows (flagged pins excepted), or a mixed kernel hash within
one campaign's safe arm is an error, not a skipped row.
"""

from __future__ import annotations

import csv
import io
import statistics
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "report" / "exhibits" / "regime-witness.md"

# (label, rev, note). Revs are pins: tags or frozen commits named in
# results/README.md / report-exhibits.py / DECISIONS entries.
PINS = [
    ("T4.3 baseline", "baseline-t4.3", ""),
    ("T4.6 after-ladder", "c40945cdb71b5aef68c5e72e292a718b66ec651e", ""),
    ("D-0068 run 1", "59e070321ab5ec30ff97830ac3f9f78577511db4", ""),
    ("D-0068 run 2", "4755fa3fe2cf98ded4dd333fa81ca66a2b811cfe", ""),
    ("T4.8", "ffb7ac71234e953ae51339a3e1f5e17ba8c3f1b3", ""),
    ("T4.8b", "t48b", "published flagship"),
    ("t47", "94bad3b8a118412639c3f2f49582141033f7b867",
     "recorded-not-published; canary ran but predates the CSV columns "
     "(console record in D-0079)"),
    ("t47b", "793680bcd4fe4174ede1ddd3ec80d9e1135b4b2b",
     "aborted, recorded-not-published; the amendment's trigger"),
]
# The divide between the two observed clusters for kernel families that
# exhibit both (ms, on page_verify). Families with a single observed
# cluster get no classification — stated per family in the output.
DIVIDE_MS = 14.0


class Fail(Exception):
    pass


def show(rev: str, path: str) -> str:
    try:
        return subprocess.check_output(
            ["git", "show", f"{rev}:{path}"], cwd=ROOT, text=True,
            stderr=subprocess.PIPE,
        )
    except subprocess.CalledProcessError as e:
        raise Fail(f"TEST FAIL: git show {rev}:{path}: {e.stderr.strip()}")


def campaign(rev: str) -> dict:
    runs = list(csv.DictReader(io.StringIO(show(rev, "results/runs.csv"))))
    phases = list(csv.DictReader(io.StringIO(show(rev, "results/phases.csv"))))
    rec = [r for r in runs if r["warmup"] == "0" and r["config"] == "release-default"]
    if not rec:
        raise Fail(f"TEST FAIL: {rev} has no recorded release-default rows")
    kern = {r["kernel_sha256"] for r in rec}
    if len(kern) != 1:
        raise Fail(f"TEST FAIL: {rev} mixed safe-arm kernel_sha256 {sorted(kern)}")
    pv = [
        int(p["delta_ns"])
        for p in phases
        if p["config"] == "release-default"
        and p["phase"] == "page_verify"
        and p["warmup"] == "0"
    ]
    if not pv:
        raise Fail(f"TEST FAIL: {rev} has no safe-arm page_verify rows")
    canary = ""
    if "canary_page_verify_ns" in rec[0] and rec[0]["canary_page_verify_ns"]:
        canary = (
            f"{int(rec[0]['canary_stvec_ns']) / 1e6:.3f}/"
            f"{int(rec[0]['canary_page_verify_ns']) / 1e6:.3f}"
        )
    batches = sorted({r["batch_id"] for r in rec})
    return {
        "kernel": next(iter(kern)),
        "n": len(pv),
        "med": statistics.median(pv) / 1e6,
        "lo": min(pv) / 1e6,
        "hi": max(pv) / 1e6,
        "canary": canary,
        "batches": batches,
    }


def main() -> int:
    rows = []
    for label, rev, note in PINS:
        c = campaign(rev)
        c.update({"label": label, "rev": rev, "note": note})
        rows.append(c)
    families: dict[str, list[dict]] = {}
    for c in rows:
        families.setdefault(c["kernel"], []).append(c)

    lines = [
        "<!-- generated by scripts/regime-witness.py — do not edit -->",
        "",
        "Regime witness reconciliation (D-0078 amendment evidence). The",
        "witness is the safe arm's recorded per-trial `page_verify`",
        "delta, read from each campaign's **pinned** CSVs; the canary",
        "columns appear where the pinned `runs.csv` carries them.",
        "Witness absolutes compare only **within one kernel family**",
        "(the safe arm's `kernel_sha256`), so rows are grouped by",
        "family; the regime divide is applied only inside a family",
        "that exhibits both clusters or a corroborating in-family boot",
        "record. Regeneration: `python3 scripts/regime-witness.py`.",
        "",
    ]
    for kern in sorted(families, key=lambda k: min(r["label"] for r in families[k])):
        fam = families[kern]
        meds = [c["med"] for c in fam]
        both = min(meds) < DIVIDE_MS < max(meds)
        # t47/t47b's family has one recorded cluster but two in-family
        # boot records below the divide (t47b's canary and its first
        # warmup, both in its pinned CSVs/serial record) — the canary
        # column itself corroborates the divide there.
        corroborated = both or any(
            c["canary"] and (float(c["canary"].split("/")[1]) < DIVIDE_MS) != (c["med"] < DIVIDE_MS)
            for c in fam
        )
        lines.append(f"### kernel family `{kern[:12]}…`")
        lines.append("")
        if corroborated:
            lines.append(
                f"Both clusters observed in this family; divide at ~{DIVIDE_MS:.0f} ms."
            )
        else:
            lines.append(
                "Single cluster observed in this family — **no regime "
                "classification**; absolutes here must not be read against "
                "other families' rows."
            )
        lines.append("")
        lines.append(
            "| campaign | n | witness med [min–max] ms | uniform | regime | "
            "canary sv/pv ms | canary vs witness |"
        )
        lines.append("|---|---:|---|---|---|---|---|")
        for c in fam:
            if corroborated:
                side = "inflated" if c["med"] >= DIVIDE_MS else "deflated"
                uniform = all(
                    (v >= DIVIDE_MS) == (c["med"] >= DIVIDE_MS)
                    for v in (c["lo"], c["hi"])
                )
                uni = "yes" if uniform else "**MIXED**"
            else:
                side, uni = "—", f"span {c['hi']-c['lo']:.2f}"
            if c["canary"]:
                c_side = "inflated" if float(c["canary"].split("/")[1]) >= DIVIDE_MS else "deflated"
                verdict = "AGREE" if (not corroborated or c_side == side) else "**DISAGREE**"
            else:
                verdict = "n/a (pre-canary)" if "canary" not in c["note"] else "n/a"
            note = f" ({c['note']})" if c["note"] else ""
            lines.append(
                f"| {c['label']}{note} | {c['n']} | {c['med']:.2f} "
                f"[{c['lo']:.2f}–{c['hi']:.2f}] | {uni} | {side} | "
                f"{c['canary'] or '—'} | {verdict} |"
            )
        lines.append("")
    lines.append(
        "The one disagreement (t47b) is the amendment's trigger: the canary "
        "read a state that flipped between the first two warmups (11.85 → "
        "16.28 ms, in the pinned phases.csv warmup rows), so the canary was "
        "correct at its instant and wrong as a certificate."
    )
    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"TEST PASS: regime-witness → {OUT}")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Fail as e:
        print(e, file=sys.stderr)
        sys.exit(1)
